# 廠商後台測試環境: https://cweb.pay2go.com
# 信用卡測試卡號:
# 4000-2222-2222-2222
# 4000-1322-2222-2222
default: &default
  merchant_id: MS31502895
  hash_key: Lj7C4ROfBSbf3ESevCV1yXSMRuTyEvxp
  hash_iv: OE1TwQ88IjnLYg0t
  url: https://ccore.spgateway.com/MPG/mpg_gateway
  notify_url: https://requestb.in/1f6vbr11

development:
  <<: *default

staging:
  <<: *default

test:
  <<: *default

production:
  <<: *default
